name: Seattle Conlang Club

domain: conlang.club
url: https://conlang.club
baseurl: ""

collections:
    handbook:
        output: true
        order:
            - phonology/sign-constituents.html
            - phonology/handshape.html
            - phonology/transcription.html
            - phonology/sign-types.html
            - links.html

plugins:
    - jekyll-postcss

postcss:
    cache: false